menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/chentao92
    About: 404
    Resume: https://chentao92.github.io/MyResume/

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: taochen
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
